version: "3"
services:
  hyperion:
    build: .
    ports:
      - "5000:5000"
    restart: always
    links:
      - db
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: hyperion
      POSTGRES_PASSWORD: 1DvaTri!
      POSTGRES_DB: hyperiondb
